baseurl = "/"
languageCode = "en-us"
title = "Geers 'n Beers"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Support Our Team!"
  cover = "images/cover.jpg"
  author = "Geers 'n Beers Team"
  # TODO authorlocation = "Paris, France"
  # TODO authorwebsite = "http://vjeantet.fr"
  bio= "Established 2017"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "erickarr"
  # twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  # [params.social]
    #twitter = "your_twitter"
